# Generated by Django 5.1 on 2024-09-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
