# Generated by Django 5.1 on 2024-12-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pledge_date_created_alter_pledge_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(),
        ),
    ]
