# Generated by Django 5.1 on 2024-12-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_date_end_alter_pledge_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
