# Generated by Django 5.1 on 2024-12-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_category_alter_pledge_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Games', 'Games'), ('Music', 'Music'), ('Art', 'Art'), ('Tech', 'Tech'), ('Film', 'Film')], default='Tech', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
