# Generated by Django 5.1 on 2024-12-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_category_alter_project_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Music', 'Music'), ('Games', 'Games'), ('Tech', 'Tech'), ('Film', 'Film')], default='Tech', max_length=100),
        ),
    ]
